tasks:
- name: "Setup"    
  command: |
    Arch=$(uname -m)
    if [[ "$Arch" == "x86_64" || "$Arch" == "amd64" ]]; then
        PLATFORM=linux_amd64
    elif [[ "$Arch" == "aarch64" || "$Arch" == "arm64" ]]; then
        PLATFORM=linux_arm64    
    else 
        echo "Unsupported platform"
        exit 1
    fi
    echo ""
    CURRENT_VERSION=$(curl -Ls https://api.github.com/repos/Versent/saml2aws/releases/latest | grep 'tag_name' | cut -d'v' -f2 | cut -d'"' -f1)
    wget -c https://github.com/Versent/saml2aws/releases/download/v${CURRENT_VERSION}/saml2aws_${CURRENT_VERSION}_${PLATFORM}.tar.gz -O - | tar -xzv -C ~/.local/bin
    chmod u+x ~/.local/bin/saml2aws
    hash -r
    saml2aws --version
vscode:
  extensions:
    - "devfactory.cloudfix-linter"
