---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CloudfixS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cloudfix-linter-cfn-test-bucket
      Tags:
      - Key: Owner
        Value: ankush.pandey@trilogy.com
  CloudfixEc2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-09d56f8956ab235b3
      InstanceType: t2.micro
      SubnetId: subnet-009f6e50e4cca6be4
      Tags:
      - Key: Owner
        Value: ankush.pandey@trilogy.com
  CloudfixVolume:
    Type: AWS::EC2::Volume
    Properties:
      VolumeType: gp2
      AvailabilityZone: us-east-1a
      Size: 8
      Tags:
      - Key: Owner
        Value: ankush.pandey@trilogy.com
  CloudfixEfs:
    Type: AWS::EFS::FileSystem
    Properties: {}
  CloudfixDynamoDb:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      KeySchema:
      - AttributeName: pk
        KeyType: HASH
      AttributeDefinitions:
      - AttributeName: pk
        AttributeType: S
      Tags:
      - Key: Owner
        Value: ankush.pandey@trilogy.com
